backends/libpurple/main.cpp

purple backend: Prevent hanging Vcard request when the plugin does not implement "get_info".
This affects e.g. the purple-facebook plugin. All VCard requests timeout after 60 seconds and no avatar (user picture) is fetched.
With this change the Vcard remains unpopulated (expected behaviour) but the avatars load.

purple backend: Prevent Vcard-Req hang when "get_info" not implemented

---

plugin/python/NetworkPlugin.py

Too much data was passed to wrapper.parseFromString resulting in it trying to read another tag even after the WrapperMessage has ended.

Prevent python plugin from crashing with InvalidWireType exception

---

backends/libpurple/CMakeLists.txt
spectrum/src/CMakeLists.txt
spectrum_manager/src/CMakeLists.txt

Fixed some build and linker issues on FreeBSD.
The linker flag "-Wl,-export-dynamic" is needed to add all symbols to the symbol table of spectrum2. Otherwise it won't find the xmpp frontend symbols in itself.

Build fixes

---

backends/libpurple/main.cpp

I have implemented the option service.verify_certs to enable certification verification for libpurple connections. This commit does not change the default behavior, however I would strongly opt for changing the default behavior.
I have tested the patch on top of a vanilla 2.0.3 version and it is currently running on my production server. I hope it will be included in the next version :)
For reference I have some logs of my testcases:
Old behavior without service.verify_certs set in a simulated MITM scenario:
```
24814: 2016-03-10 23:14:46,003 INFO  libpurple: nss:CERT 2. CN=GeoTrust Global CA,O=GeoTrust Inc.,C=US [Certificate Authority]:
24814: 2016-03-10 23:14:46,003 INFO  libpurple: nss:  ERROR -8172: SEC_ERROR_UNTRUSTED_ISSUER
24814: 2016-03-10 23:14:46,003 INFO  backend: accepting SSL …
```

Libpurple: Add service.verify_certs option to enable certificate verification

---

backends/libpurple/main.cpp
backends/smstools3/main.cpp
backends/swiften/main.cpp
backends/twitter/HTTPRequest.cpp
backends/twitter/Requests/CreateFriendRequest.cpp
backends/twitter/Requests/DestroyFriendRequest.cpp
backends/twitter/Requests/DirectMessageRequest.cpp
backends/twitter/Requests/FetchFriends.cpp
backends/twitter/Requests/PINExchangeProcess.cpp
backends/twitter/Requests/ProfileImageRequest.cpp
backends/twitter/Requests/RetweetRequest.cpp
backends/twitter/Requests/StatusUpdateRequest.cpp
backends/twitter/Requests/TimelineRequest.cpp
backends/twitter/TwitterPlugin.cpp
backends/twitter/TwitterResponseParser.cpp
backends/twitter/main.cpp
libtransport/HTTPRequest.cpp
libtransport/ThreadPool.cpp
libtransport/User.cpp
libtransport/UserManager.cpp
spectrum/src/frontends/slack/SlackSession.cpp
spectrum/src/frontends/xmpp/XMPPUserRegistration.cpp
spectrum/src/main.cpp

General cleanup

---

backends/libpurple/main.cpp

The author of `purple-hangouts` has [changed the prompt](https://bitbucket.org/EionRobb/purple-hangouts/commits/cae4ef68df6977042e36edbc39b60215ae70b199) for the OAuth code. This patch allows accepting either the old or new prompt.
With this change I was able to authenticate with Hangouts using the latest `purple-hangouts` master.

Accept updated purple-hangouts primary prompt

---

backends/libcommuni/session.cpp

Fixes compilation issue
```
[ 64%] Building CXX object backends/libcommuni/CMakeFiles/spectrum2_libcommuni_backend.dir/session.cpp.o
cd /var/tmp/portage/net-im/spectrum-9999/work/spectrum-9999/backends/libcommuni && /usr/bin/x86_64-pc-linux-gnu-g++ -DBOOST_FILESYSTEM_VERSION=3 -DDEBUG -DIRC_SHARED -DPURPLE_RUNTIME=0 -DQT_CORE_LIB -DQT_NETWORK_LIB -DQT_NO_KEYWORDS -DSPECTRUM_VERSION=\"2.0.5-git-b15fcedf\" -DSUPPORT_LEGACY_CAPS -DWITH_LIBEVENT -DWITH_LOG4CXX -DWITH_PQXX -DWITH_PROTOBUF -isystem /usr/include/qt4 -isystem /usr/include/qt4/QtCore -I/usr/include/libpurple -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -isystem /usr/include/qt4/QtNetwork -I/usr/include/qt4/Communi/IrcCore -I/usr/include/qt4/Communi/IrcUtil -I/usr/include/qt4/Communi/IrcModel …
```

Define 'foreach' in backends/libcommuni/session.cpp

---

include/transport/NetworkPluginServer.h
libtransport/NetworkPluginServer.cpp

This was suggested in #233 .
This fixes display of incoming images in clients which don't support XHTML (like Conversations), and (as far as I can see) works at least for Telegram and Hangouts.

Wrap incoming images in x:oob tag

---

packaging/debian/debian/spectrum2.service

Thanks to that, "systemctl enable spectrum2" does what expected, that is
makes Spectrum2 start on boot. Also, network.target doesn't tell anything
meaningful - it's just that the network stack is available.
Adding network-online.target makes sure that the network interfaces are up
before starting Spectrum2.

systemd: wait for network-online.target and add WantedBy=multi-user.target

---

libtransport/NetworkPluginServer.cpp

Not setting it violated XEP-0085 and sometimes tricked other clients
into thinking that Spectrum does not understand chat states.
Closes #282

libtransport: set active chat state on conversation message

---

backends/libpurple/main.cpp
backends/libpurple/purple_defs.h

I patched the libpurple backend to store and retrieve the Steam Mobile access token to and from the database. This is a partial fix for #264.
I'm not 100% sure whether this is correctly implemented, but it works for me this way. Maybe someone with more C++ knowledge can check and optimize it.

Store Steam Mobile access token in storage backend

---

libtransport/NetworkPluginServer.cpp

There appears to be a missing semicolon on line 1818 of `NetworkPluginServer.cpp`. This causes compilation to fail with the following error message when using the latest git version of log4cxx.
```
spectrum2/src/spectrum2-2.0.7/libtransport/NetworkPluginServer.cpp: In member function ‘void Transport::NetworkPluginServer::wrapIncomingImage(Swift::Message*, const pbnetwork::ConversationMessage&)’:
spectrum2/src/spectrum2-2.0.7/libtransport/NetworkPluginServer.cpp:1819:9: error: expected ‘;’ before ‘}’ token
```

libtransport: add missing semicolon

---

backends/libpurple/main.cpp

Recent prpl-steam-mobile version changed the input message for *steam guard*. This should fix #301

Fix two factor authenthication with steam

---

backends/libcommuni/ircnetworkplugin.cpp

... by splitting them into one PRIVMSG command per line.
Closes #305

libcommuni IRC backend: support multi-lines messages

---

backends/libpurple/main.cpp
libtransport/Config.cpp

1. If we cannot treat image as an image (web_directory disabled, image too large), treat it as a standard message at least (strip non-XHTML and forward what remains).
2. If there's nothing left after stripping out non-XHTML tags, send "[The user sent you an image]" (it's confusing if messages silently not arrive at all)
3. Added a configuration option web_maximgsize to set max image filesize (had been hardcoded to 1Mb)
4. If we already have that image in web_directory by hash, do not rewrite its contents (saves a bit of time I guess) but do update mtime
5. Fix: better quote handling when replacing ``<img id= />`` tags.
6. Fix: plaintext generated manually during the ``<img id= />`` tag replacement must still be purple_html_to_xhtmled because it can contain unrelated html snippets. (Or …

Image handling improvements

---

backends/libpurple/main.cpp
include/transport/Logging.h
include/transport/NetworkPlugin.h
include/transport/RosterManager.h
libtransport/Config.cpp
libtransport/RosterManager.cpp
plugin/cpp/networkplugin.cpp
spectrum/src/sample2_gateway.cfg

1. Fixed Issue 324's part about rejected friend requests remaining and getting redelivered.
2. Refactored the subscription code and added some comments.
Made it so that Subscribe/Subscribed and Unsubscribe/Unsubscribed work the same for the gateway. Previously it had been halfway: e.g. Unsubscribe fully removes the buddy while Unsubscribed does nothing. If anything, I think it makes more sense to remove them on Unsubscribed, because
Subscribe = please give me your status updates
Subscribed = I allow you my status updates
Unsubscribe = please deny me your status updates
Unsubscribed = I deny you my status updates
Spectrum seems to follow Pidgin model where you can only be mutual friends or neither, so 1+2 and 3+4 should only happen in pairs, which can be triggered by either action.
3. …

Friend request handling improvements

---

backends/libpurple/main.cpp

A simple fix for #351 supporting Steam Guard Mobile Authenticator in addition to Email.

Support Steam Guard for Mobile Authenticator and Email

---

spectrum/src/frontends/xmpp/carbonresponder.cpp

There's a missing semicolon on line 33 of `carbonresponder.cpp` that causes build failures with newer versions of `log4cxx`. Compilation fails with this error message:
```
error: expected ‘;’ before ‘discoInfoResponder’ discoInfoResponder->addTransportFeature("urn:xmpp:carbons:2");
```

xmpp: add missing semicolon

---

backends/frotz/dfrotz/dumb/dumb_init.c
backends/frotz/dfrotz/dumb/dumb_input.c
backends/frotz/dfrotz/dumb/dumb_output.c

Since GCC enables by default -fno-common,
the compilation of dfrotz due multiple definitions will fail.
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>

Fix dfrotz compilation with GCC >= 10

---

spectrum/src/frontends/xmpp/discoinforesponder.cpp

* Some clients does not want to browse items without disco#items feature

Fix service discovery of transport JID

---

spectrum_manager/src/managerconfig.cpp
spectrum_manager/src/server.cpp
spectrum_manager/src/spectrum_manager.cfg

The default spectrum2 ui onfig listens to all interfaces, even if not set up. As the systemd service will start by default the server, this can have security implications.
(This is a patch from the upcoming Debian package)

Allow the possiblity to bind only to localhost and do that by default.

---

CMakeLists.txt
include/transport/CMakeLists.txt
libtransport/CMakeLists.txt
plugin/cpp/CMakeLists.txt
spectrum/src/CMakeLists.txt
spectrum_manager/src/CMakeLists.txt

The installation target directories might be different on different distributions. For example, Debian using multiarch tuples paths for the libraries.
CMake provided a facility to set up certain variables to that the files will get installed into the correct directories. More details:
https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html

Use GNUInstallDirs to setup installation target directories.

---

backends/libcommuni/CMakeLists.txt
backends/libpurple/CMakeLists.txt
backends/smstools3/CMakeLists.txt
backends/swiften/CMakeLists.txt
backends/twitter/CMakeLists.txt
spectrum/src/sample2.cfg
spectrum/src/sample2_gateway.cfg

(note: this requires #456 to be merged first. Splitted so that this topic can be properly discussed as this might be a breaking change:))
IIUIC the backends are not supposed to be executed directly by the user, but spawned using spectrum2_manager. In this case, the binaries should not be in $PATH, i.e outside of /usr/bin.
This patch installs the backends to /usr/libexec [1], as this matches the FSH intention for this directory.
[1] https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s07.html

Install backends to /usr/libexec instead of /usr/bin (which is in $PATH)

---

spectrum_manager/src/server.cpp
spectrum_manager/src/spectrum_manager.cfg

Well, this is aimed to protect the unaware or the dontcare for inadvertently opening up their spectrum2 webinterface to the world, creating all sorts of security issues on the way…
(I'm using this patch for the Debian package for a hardened default setup; when the user installs the webinterface package, this will automatically also start it, so this is needed for an secure user experience…)

Reject empty password and "test" for the webinterface.

---

plugin/cpp/Util.cpp
spectrum/src/main.cpp
spectrum_manager/src/methods.cpp

Compilation with boost-1.85 will fail, as the filesystem api v4 removed deprecated features.
See https://www.boost.org/doc/libs/1_85_0/libs/filesystem/doc/deprecated.html.
More info on: https://bugs.gentoo.org/933691

Fix compilation with boost-1.85

---

.github/workflows/main.yml
CMakeLists.txt
backends/frotz/CMakeLists.txt
backends/libcommuni/CMakeLists.txt
backends/libpurple/CMakeLists.txt
backends/smstools3/CMakeLists.txt
backends/swiften/CMakeLists.txt
backends/template/CMakeLists.txt
libtransport/CMakeLists.txt
plugin/cpp/CMakeLists.txt
spectrum/src/CMakeLists.txt
spectrum/src/frontends/slack/CMakeLists.txt
spectrum/src/frontends/xmpp/CMakeLists.txt
spectrum_manager/src/CMakeLists.txt
tests/libtransport/CMakeLists.txt

* This will allow to override with -DCMAKE_CXX_STANDARD=20
Fixes [#496](https://github.com/SpectrumIM/spectrum2/issues/496)

CMake: set c++ standard using `target_compile_features`

---

.github/workflows/main.yml

Potential fix for [https://github.com/SpectrumIM/spectrum2/security/code-scanning/29](https://github.com/SpectrumIM/spectrum2/security/code-scanning/29)
To fix this problem, you should explicitly specify the `permissions` key at the root of the workflow YAML file, before the `jobs` section. This will constrain the GITHUB_TOKEN to only have the privileges needed for the workflow. Since the jobs perform code checkout, build, and test, but do not appear to require write permissions, the minimal required permission is `contents: read`. This permissions block should be added at the top level of `.github/workflows/main.yml`, ideally immediately after the `name:` and `on:` sections, before the `jobs:` key. No additional imports or changes are necessary; simply add:
```yaml
permissions:
contents: …
```

Potential fix for code scanning alert no. 29: Workflow does not contain permissions

---

spectrum/src/CMakeLists.txt

'-Wl,-export-dynamic' will be interpreted as '-Wl,-e xport-dynamic'.

cmake: fix -Wl,--export-dynamic typo
