packaging/debian/build_spectrum2.sh
Can't package if missing devscripts deb
=> Check debuild presence

documentation/tutorials/beginners_guide.md
I really don't know if this follows the project guidelines or anything but I felt like new users would really need a guide.
P.S.: I'm haztest from the Spectrum 2 conference room
=> First draft of install guide for beginners

Dockerfile
There is a new purple-facebook release available. This PR adds it to the Dockerfile.
=> Dockerfile: Update purple-facebook

include/transport/RosterManager.h, libtransport/RosterManager.cpp, spectrum/src/frontends/xmpp/XMPPRosterManager.cpp
Has to be std::pair<const Key, T>
=> Fix value_type definition of std::map.

Dockerfile
Its currently untested, will test it the next days
=> Added Discord & fixed telegram cleanup

Dockerfile, backends/libpurple/main.cpp
by using https://github.com/EionRobb/pidgin-opensteamworks
Closes #62 component will contact user for steam guard and will login if received.
@vitalyster
=> Added opensteamworks via libpurple

README.md
I just updated the URL in the Travis Build Link in the README.MD file.
=> Updated Travis Build Link

Dockerfile
=> Upgrade purple facebook to 0.9.5

Dockerfile
Add purple-hangouts from Fedora repositories to the Dockerfile
=> Add purple-hangouts to Dockerfile

README.md, appveyor.yml
=> appveyor: no need to cache dist folder

Dockerfile
Changed yowsup repo to  maintained one
=> add new repo for yowsup

backends/libpurple/main.cpp
Treats each ``<img>`` separately: those that cannot be processed will be replaced with "[The user has sent you an image]" inplace, instead of the message as a whole.
This covers cases where there are several ``<img>``s 
```
```
Or there are other tags which stop this almost empty message from being treated as empty:
```
<br /><img id=1> 
```
=> Images: inplace placeholders if rehosting fails

libtransport/RosterManager.cpp
Restored the Unsubscribe/Unsubscribed distinction after some thinking. ``<unsubscribed>`` may be a reply to a ``<subscribe>`` request, and even to a formal one sent for a Buddy::Both when roster_sync is unavailable. This rejection should not delete the buddy.
``<unsubscribe>`` meanwhile is an explicit action and usually only happens when people delete contacts from their rosters.
=> Fix: Do not remove existing legacy buddies on formal XMPP <subscribe>rejections

Dockerfile
=> added icque

Dockerfile
=> added purple-instagram

documentation/development/protocol.md
I also reference the new pyspectrum2 package
=> Add a section pointing to the backend template code

include/transport/ThreadPool.h
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>
=> Fix compilation with boost-1.73

Dockerfile
* multistage build to reduce final image size
* remove broken transwhat plugin
* added purple-telegram-tdlib
=> Docker: switch to Debian base image

backends/libpurple/main.cpp
=> prpl-eionrobb-instagram 2FA support

include/transport/MySQLBackend.h, include/transport/PQXXBackend.h, include/transport/SQLite3Backend.h, include/transport/StorageBackend.h, libtransport/MySQLBackend.cpp, libtransport/PQXXBackend.cpp, libtransport/SQLite3Backend.cpp, spectrum/src/frontends/xmpp/XMPPUserRegistration.cpp, tests/libtransport/basictest.h
=> Do not allow multiple registrations with the same id for password-less backends

Dockerfile
* apply lint suggestions
* use purple-xmpp-carbons package from bullseye
=> Dockerfile: minor updates

backends/frotz/main.cpp, backends/libcommuni/ircnetworkplugin.cpp, backends/libcommuni/ircnetworkplugin.h, backends/libpurple/CMakeLists.txt, backends/libpurple/main.cpp, backends/smstools3/main.cpp, backends/swiften/main.cpp, backends/template/plugin.cpp, backends/template/plugin.h, backends/twitter/TwitterPlugin.cpp, backends/twitter/TwitterPlugin.h, include/transport/MySQLBackend.h, include/transport/NetworkPlugin.h, include/transport/PQXXBackend.h, include/transport/SQLite3Backend.h, include/transport/StorageBackend.h, include/transport/User.h, include/transport/protocol.proto, libtransport/MySQLBackend.cpp, libtransport/NetworkPluginServer.cpp, libtransport/PQXXBackend.cpp, libtransport/SQLite3Backend.cpp, libtransport/UserManager.cpp, plugin/cpp/networkplugin.cpp, tests/libtransport/basictest.h, tests/libtransport/settingsadhoccommand.cpp
Do not delete accounts.xml, this will allow to simplify plugin a lot: no need in storage backend, no need to save/restore settings, etc
=> libpurple: save accounts.xml

Dockerfile
Bump purple-gowhatsapp from 1.1.0 to 1.2.0
=> Bump gowhatsapp version

Dockerfile
Bump libpurple-gowhatsapp version to 1.6.0
=> Bump libpurple-gowhatsapp

Dockerfile
Bump purplegowhatsapp version to 1.8.0
=> Bump gowhatsapp version to 1.8.0

tests/CMakeLists.txt
As the title says, run the tests only if ENABLE_TESTS is On.
=> Run test only when ENABLE_TESTS is On

Dockerfile
Hi vt
I took some user requests and did work in regard to voice messages.
Also, I moved some code into git submodules. `--recursive` is needed during checkout.
Caveat: I did not check these changes in Spectrum, only Pidgin.
Kind Regards
Hermann
=> Update Dockerfile for purple-gowhatsapp 1.13.0
